default:
  suites:
    default:
      contexts:
        - DrupencyContext
        - Drupal\DrupalExtension\Context\MinkContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      base_url: http://127.0.0.1:8888
      files_path: ../../
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      # You need to set drupal - drupal_root with BEHAT_PARAMS
      # export BEHAT_PARAMS='{"extensions":{"Drupal\\DrupalExtension":{"drupal":{"drupal_root":"$DISTRO/docroot"}}}}'
      drush:
        alias: self
      region_map:
        Tabs: ".tabs.primary"
      text:
        password_field: "pass"
        username_field: "name"
        log_in: "Log in"
        log_out: "Log out"